version: "3.7"

services: 
  db_locadora:
    image: postgres
    container_name: db_locadora
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: locadora
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - db_locadora
    depends_on: 
      - db_locadora

volumes:
  pgdata: 
    driver: local